### PR TITLE
preserve hot directories across GC

### LINKED ISSUE #32: GC should not remove data from latest incremental build
We run GC with a space factor of 20% and when the disk is getting full, we cannot even pass a single build as GC removes the latest build in `bake-incremental.txt` which is then not usable by subsequent builds. GC should never remove directory pointed at `bake-incremental.txt` nor currently in use directory.

### PR DESCRIPTION
**Pull request by abailly**
preserves direcotry pointed at by bake-incremental.txt as well as store when running a GC.
Those directories will never get collected. this should fix #32

### CODE REVIEW

**Comment by ndmitchell** [comment]
Seems entirely reasonable. I'm on mobile til thur but will merge it then.

**Comment by abailly** [comment]
Wondering if this should not also preserve bake-extra-xxx and
bake-string-xxx directories? Then why not merge all tests output into a
single directory per test with subdirs for each kind o output ?

Le mardi 15 décembre 2015, Neil Mitchell <notifications@github.com> a
écrit :

> Seems entirely reasonable. I'm on mobile til thur but will merge it then.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndmitchell/bake/pull/33#issuecomment-164898791>.
>


-- 
-- 
Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/

**Comment by abailly** [comment]
Because I did not care to write tests, the previous commit was of course wrong... I pushed a quick fix because I need to keep production running here but I will definitely add unit tests.

**Comment by ndmitchell** [comment]
I can't compile Warp at the moment (https://github.com/yesodweb/wai/issues/495), but the latest version of Warp/Wai breaks Bake (https://travis-ci.org/ndmitchell/bake/jobs/89409244). I'll have to wait for those things to get fixed first so I can actually get this code working and play with it.

I assume there's no great hurry on your side, as you'll have either found a workaround in production, or be running your branch. If that's not true, and there's great value to merging this sooner, let me know and I'll merge and review after-the-fact.

**Comment by abailly** [comment]
Hi Neil,
You are right I am running our own branch which includes this patch so no
hurry, indeed.

Have a Merry Christmas !

-- 
Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/

**Comment by ndmitchell** [comment]
And Merry Christmas to you too!

**Comment by ndmitchell** [comment]
I've definitely stopped working on Bake, but your improvements look useful, so I've merged them in case anyone wants to build on what I've done thus far. If you ever do decide to become "the Bake guy" let me know and I'll update this readme to point at wherever you put the new version.

**Comment by abailly** [comment]
Thanks @ndmitchell ! I don't use bake anymore, unfortunately I should say, as I now have to go through the throes of working with some cloud-provided CI... 😞 I would be happy to take it over as I think it has some great ideas but don't have any bandwidth for that now.

**Comment by ndmitchell** [comment]
Yep, everyone is rather bandwidth constrained! It was enjoyable collaborating on Bake, so do let me know if you are ever passing through Cambridge, UK and I'll buy you a beer.

**Comment by abailly** [comment]
That would be awesome! I go there from time to time so I definitely will do
:)

BTW, Happy New Year!

-- 
Arnaud Bailly - @dr_c0d3

**Pull request merged**
