### PR TITLE
retry failed connections when sending messages

### PR DESCRIPTION
**Pull request by abailly**
This is a possibly very crude attempt at fixing a recurring issue of mine working with bake: I startup bake's server and client as docker containers through docker-compose, and there is no way to ensure orderly startup from here, hence I make sure client will wait a certain amount of time for server to be up before giving up and failing.

### CODE REVIEW

**Comment by ndmitchell** [comment]
Could I get the patch without the import and LANGUAGE pragma whitespace changes? They somewhat obscure the rest of the patch, make the diff much larger, and also end up with the import style/LANGUAGE style different to the rest of the project.

On the technical side, this seems a good idea - I've had random issues with Bake falling over in my deployment due to a network split that resolves itself momentarily. 3 retires seems sensible. I wonder if 30s between retries is too long? Would 10s be enough for your case? That still gives you 30s from first to last retry, but doesn't give you a potential 90s before declaring failure (which seems on the long side). However, those timings are just what "feels" right, so if you have any evidence I'd be happy to hear it.

**Comment by abailly** [comment]
Oh, sure, I have stylish-haskell up all the time and it reformatted imports. 3 x 30s might be a bit long, yes. In my particular use case, 3 x 10s should be enough as containers spin up quite fast. I will change it that way and fix the patch.

**Comment by ndmitchell** [comment]
I added a couple of patches on top, let me know if they harm it. I introduced a `retrySleep` function which generalises the retry logic. There are two functional changes:

* The final retry doesn't get caught and rethrown, just never caught, which gives better error messages/stacks where available.
* The test doesn't fail if the exception is of the right type but not that particular constructor.

**Comment by abailly** [comment]
Nice!

**Pull request merged**
